### ISSUE TITLE
How to find out there is no ad to show! 

### ISSUE THREAD

**Issue by IRMobydick** [MagnetAdServices/magnet-android-sdk#1]
Hi there,
Sometimes `MagnetSDK` Does not provide ads to show in native state and create an ugly empty space in list.
How can find there is ads or not to prevent adding Ads object to adapter?

**Comment by MagnetAdServices** [comment]
This is fixed in new version of magnet SDK. Please update your android SDK.

**Comment by IRMobydick** [comment]
And what about `Memory Leak` in native state? Does it solved too?

**Comment by IRMobydick** [comment]
package name got changed to `com.magnetadservices.sdk` :|
and you don't mention it anywhere!

**Comment by MagnetAdServices** [comment]
You are right.
this repo will update as soon.
sorry about that.
