### ISSUE TITLE
MemoryLeak in Native ( Hamsan ) state

### ISSUE THREAD

**Issue by IRMobydick** [MagnetAdServices/magnet-android-sdk#2]
There is Memory leaking in native state!

In our app

    com..............activities.MainActivity has leaked:
    GC ROOT static com.magnetadservices.sdk.o.a
    leaks com..............activities.MainActivity instance

    Retaining: 5.4 MB.
    Reference Key: 31a94c2c-da55-4c08-b7d0-cf442b42875e
    Device: samsung samsung SM-G900H k3gxx
    Android Version: 6.0.1 API: 23 LeakCanary: 1.5 00f37f5
    Durations: watch=5231ms, gc=169ms, heap dump=6647ms, analysis=43034ms

    Details:
    Class com.magnetadservices.sdk.o
    static $staticOverhead = byte[8]@316395009 (0x12dbce01)
    static a = com..............activities.MainActivity@317023440 (0x12e564d0)

**Comment by MagnetAdServices** [comment]
Yes, we had a report of a leak in native Ad.
this task will handle in new version (in next week)
thank you for reporting.

**Comment by IRMobydick** [comment]
Any update? 😕

**Comment by IRMobydick** [comment]
👍 👍
